# Generated by Django 5.2.17 on 2026-09-16 20:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('group', models.CharField(default='9A', max_length=40)),
                ('is_demo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.FloatField(default=70, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('partial', models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('required', models.FloatField(default=80, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('similarity', models.FloatField(default=0.45, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.99)])),
                ('reference_count', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('lost_seconds', models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(5)])),
                ('width', models.PositiveIntegerField(default=640, validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(1920)])),
                ('height', models.PositiveIntegerField(default=480, validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(1080)])),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=80)),
                ('detail', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('new', 'Sin iniciar'), ('live', 'En curso'), ('paused', 'Pausada'), ('finished', 'Finalizada'), ('interrupted', 'Interrumpida')], default='new', max_length=16)),
                ('camera', models.PositiveIntegerField(default=0)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('heartbeat', models.DateTimeField(blank=True, null=True)),
                ('review', models.BooleanField(default=False)),
                ('present_threshold', models.FloatField(default=70)),
                ('partial_threshold', models.FloatField(default=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.course')),
            ],
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('student', 'Estudiante'), ('visitor', 'Visitante'), ('intruder', 'Posible intruso'), ('ignored', 'Ignorado')], default='pending', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.course')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='classroom.classsession')),
                ('identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.identity')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('observations', models.PositiveIntegerField(default=1)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.identity')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='classroom.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reference_images/%Y/%m/')),
                ('embedding', models.JSONField(default=list)),
                ('model', models.CharField(default='sface-2021dec', max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='classroom.identity')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='classroom.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='classroom.identity')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classroom.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='one_participant')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='one_enrollment')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('result', models.CharField(default='absent', max_length=16)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='classroom.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='one_attendance')],
            },
        ),
    ]
