# Generated by Django 5.2.17 on 2026-09-18 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='away_brief',
            field=models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(7200)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='away_long',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(14400)]),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='away_notice',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)]),
        ),
    ]
